name: four-machine-large
description: Larger scheduling instance with four machines and tighter deadlines.
machines: 4
jobs:
  - id: J1
    processing_time: 9
    due_date: 28
    weight: 3.4
  - id: J2
    processing_time: 6
    due_date: 22
    weight: 2.5
  - id: J3
    processing_time: 8
    due_date: 27
    weight: 2.9
  - id: J4
    processing_time: 5
    due_date: 18
    weight: 2.2
  - id: J5
    processing_time: 7
    due_date: 24
    weight: 2.8
  - id: J6
    processing_time: 10
    due_date: 36
    weight: 3.6
  - id: J7
    processing_time: 4
    due_date: 15
    weight: 1.6
  - id: J8
    processing_time: 6
    due_date: 21
    weight: 2.1
  - id: J9
    processing_time: 5
    due_date: 19
    weight: 1.9
  - id: J10
    processing_time: 7
    due_date: 26
    weight: 2.7
  - id: J11
    processing_time: 9
    due_date: 33
    weight: 3.1
  - id: J12
    processing_time: 6
    due_date: 20
    weight: 2.0
  - id: J13
    processing_time: 8
    due_date: 29
    weight: 2.6
  - id: J14
    processing_time: 5
    due_date: 17
    weight: 1.8
  - id: J15
    processing_time: 6
    due_date: 23
    weight: 2.3
  - id: J16
    processing_time: 7
    due_date: 25
    weight: 2.5
  - id: J17
    processing_time: 4
    due_date: 14
    weight: 1.5
  - id: J18
    processing_time: 9
    due_date: 30
    weight: 3.2
