#!/usr/bin/env python3
"""Generate qsharp/RuntimeConfig.qs from CLI/runtime parameters."""

from __future__ import annotations

import argparse
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Write Q# runtime config constants")
    parser.add_argument("--loss-qubits", type=int, required=True)
    parser.add_argument("--threshold", type=float, required=True)
    parser.add_argument("--mean", type=float, required=True)
    parser.add_argument("--std-dev", type=float, required=True)
    parser.add_argument("--precision-bits", type=int, required=True)
    parser.add_argument("--repetitions", type=int, required=True)
    parser.add_argument("--run-sanity-check", required=True, choices=["true", "false", "True", "False", "1", "0"])
    parser.add_argument(
        "--runtime-config-file",
        default="../qsharp/RuntimeConfig.qs",
        help="Path to RuntimeConfig.qs to write",
    )
    return parser.parse_args()


def _bool_literal(value: str) -> str:
    return "true" if value.lower() in {"true", "1"} else "false"


def main() -> int:
    args = parse_args()
    script_dir = Path(__file__).resolve().parent
    runtime_config_path = (script_dir / args.runtime_config_file).resolve()

    runtime_content = f"""namespace QuantumGrandChallenges.QAERisk {{
    // Auto-generated by python/write_runtime_config.py.
    function RuntimeLossQubits() : Int {{
        return {int(args.loss_qubits)};
    }}

    function RuntimeThreshold() : Double {{
        return {float(args.threshold)};
    }}

    function RuntimeMean() : Double {{
        return {float(args.mean)};
    }}

    function RuntimeStdDev() : Double {{
        return {float(args.std_dev)};
    }}

    function RuntimePrecisionBits() : Int {{
        return {int(args.precision_bits)};
    }}

    function RuntimeRepetitions() : Int {{
        return {int(args.repetitions)};
    }}

    function RuntimeRunSanityCheck() : Bool {{
        return {_bool_literal(args.run_sanity_check)};
    }}
}}
"""

    runtime_config_path.write_text(runtime_content, encoding="utf-8")
    print(f"Updated runtime config file at {runtime_config_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
