// Publishes the Blender visualisation output into the static site.
//
// viz/ is workstream B's; website/ is D's. The contract is that B writes
// viz/manifest.json plus assets and never edits .tsx, and the site reads the
// manifest and never edits the render pipeline. This script is that seam.
//
// The 20 posters are ~29.5 MB and already tracked under viz/assets. Copying them
// into website/public and committing them would double that in git, so the copies
// are gitignored and regenerated here on every build (npm `prebuild`).
//
// Every asset is checked against the sha256 the manifest declares. A poster that
// has drifted from its manifest entry fails the build rather than shipping: an
// image is a claim about a run, and an unverified copy is not evidence.
//
// Deliberately omitted from the published manifest: qubit counts. The site already
// reads those from data/resourceEstimates.json, and a second copy here would be a
// second source of truth for the exact numbers #263 existed to converge.

import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const WEBSITE = resolve(HERE, '..');
const REPO = resolve(WEBSITE, '..');
const VIZ = join(REPO, 'viz');

const MANIFEST_IN = join(VIZ, 'manifest.json');
const PUBLIC_OUT = join(WEBSITE, 'public', 'viz');
const MANIFEST_OUT = join(WEBSITE, 'data', 'vizManifest.json');

function sha256(buf) {
  return createHash('sha256').update(buf).digest('hex');
}

function fail(message) {
  console.error(`publish-viz: ${message}`);
  process.exit(1);
}

if (!existsSync(MANIFEST_IN)) {
  fail(`no manifest at ${MANIFEST_IN}. Run the viz pipeline first (see viz/README.md).`);
}

const manifest = JSON.parse(readFileSync(MANIFEST_IN, 'utf8'));

if (manifest.schema_version !== '1.0') {
  fail(
    `manifest schema_version is ${JSON.stringify(manifest.schema_version)}, expected "1.0". ` +
      `The contract changed; update this publisher rather than loosening the check.`,
  );
}

// Rebuilt from scratch so a poster deleted upstream cannot linger in the site.
rmSync(PUBLIC_OUT, { recursive: true, force: true });
mkdirSync(PUBLIC_OUT, { recursive: true });

const published = [];
let skipped = 0;

for (const problem of manifest.problems) {
  const asset = (problem.assets ?? [])[0];

  if (problem.render_status !== 'rendered' || !asset) {
    // Not an error: the schema allows a problem to be pending with no asset.
    skipped += 1;
    continue;
  }

  const source = join(VIZ, asset.path);
  if (!existsSync(source)) {
    fail(
      `${problem.id}: manifest declares ${asset.path} but the file is missing. ` +
        `The manifest and the assets are out of step.`,
    );
  }

  const bytes = readFileSync(source);
  const actual = sha256(bytes);
  if (actual !== asset.sha256) {
    fail(
      `${problem.id}: ${asset.path} hashes to ${actual.slice(0, 12)} but the manifest ` +
        `declares ${asset.sha256.slice(0, 12)}. Regenerate the manifest, or restore the asset.`,
    );
  }

  const destDir = join(PUBLIC_OUT, problem.id);
  mkdirSync(destDir, { recursive: true });
  writeFileSync(join(destDir, 'poster.png'), bytes);

  published.push({
    id: problem.id,
    title: problem.title,
    stage: problem.stage,
    archived: problem.archived,
    poster: {
      // Site-root relative. The page applies basePath, as the rest of the site does.
      src: `/viz/${problem.id}/poster.png`,
      width: asset.width,
      height: asset.height,
      alt: asset.alt,
    },
    // Carried through deliberately and rendered next to the image. A render that
    // looks like a quantum state, shown without the caveat saying it is not one,
    // is the kind of over-claim this project exists to avoid.
    warnings: problem.warnings ?? [],
  });
}

if (published.length === 0) {
  fail('no rendered assets found in the manifest; the site would show nothing.');
}

writeFileSync(
  MANIFEST_OUT,
  `${JSON.stringify(
    {
      schema_version: manifest.schema_version,
      source: 'viz/manifest.json',
      note: 'Generated by website/scripts/publish-viz.mjs. Do not edit by hand.',
      problems: published,
    },
    null,
    2,
  )}\n`,
  'utf8',
);

console.log(
  `publish-viz: ${published.length} posters verified and published` +
    (skipped ? `, ${skipped} not yet rendered` : ''),
);
