"""Expand the algorithm zoo index with algorithms from quantumalgorithmzoo.org."""
import json
from datetime import datetime, timezone
from pathlib import Path

ZOO_PATH = Path(__file__).resolve().parent.parent / "knowledge" / "data" / "algorithm_zoo_index.json"

NEW_ALGORITHMS = [
    {"name": "Discrete Logarithm", "category": "Number Theory / Cryptography", "speedup_class": "superpolynomial", "quantum_complexity": "O(n^3)", "classical_best": "Index calculus (sub-exponential)", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "Breaks Diffie-Hellman and ECDSA. Same core technique as Shor (hidden subgroup over Z).", "reference": "arXiv:quant-ph/9508027"},
    {"name": "Abelian Hidden Subgroup", "category": "Group Theory", "speedup_class": "superpolynomial", "quantum_complexity": "O(polylog(|G|))", "classical_best": "O(|G|^(1/2))", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "Generalizes Shor, Simon, Deutsch-Jozsa. Core primitive for period finding. Uses QFT over finite Abelian groups.", "reference": "arXiv:quant-ph/0411037"},
    {"name": "Quantum Cryptanalysis", "category": "Cryptography", "speedup_class": "superpolynomial", "quantum_complexity": "Varies by target", "classical_best": "Varies (GNFS, index calculus, etc.)", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "Breaks RSA, DSA, ECDSA, Diffie-Hellman. Subexponential attack on isogeny-based crypto. Polynomial speedups against symmetric ciphers via Grover.", "reference": "arXiv:1804.00200"},
    {"name": "Pell's Equation", "category": "Number Theory", "speedup_class": "superpolynomial", "quantum_complexity": "poly(n)", "classical_best": "No known polynomial-time algorithm", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "Hallgren 2002. Solves x^2 - dy^2 = 1. Breaks Buchman-Williams cryptosystem. Reduces to Abelian hidden subgroup.", "reference": "Hallgren STOC 2002"},
    {"name": "Bernstein-Vazirani", "category": "Oracle / Learning", "speedup_class": "superpolynomial", "quantum_complexity": "O(1) queries", "classical_best": "O(n) queries", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "Finds hidden bit string with single query. Recursive version gives exponential separation. Foundational for quantum learning theory.", "reference": "arXiv:quant-ph/9301023"},
    {"name": "Deutsch-Jozsa", "category": "Oracle / Decision", "speedup_class": "exponential_deterministic", "quantum_complexity": "O(1) queries", "classical_best": "O(2^(n-1)+1) deterministic, O(1) probabilistic", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "INCONCLUSIVE", "notes": "First quantum algorithm showing speedup. Exponential deterministic advantage but no advantage over randomized classical. Historical importance.", "reference": "Deutsch-Jozsa 1992"},
    {"name": "Simon's Algorithm", "category": "Oracle / Period Finding", "speedup_class": "superpolynomial", "quantum_complexity": "O(n) queries", "classical_best": "O(2^(n/2)) queries", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "Finds hidden period of 2-to-1 function. Inspired Shor's algorithm. First provable exponential quantum speedup for promise problem.", "reference": "Simon FOCS 1994"},
    {"name": "Collision Finding", "category": "Cryptography / Hash Functions", "speedup_class": "polynomial", "quantum_complexity": "O(N^(1/3))", "classical_best": "O(N^(1/2)) birthday attack", "io_bottleneck": True, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "HPC_PREFERRED", "notes": "Brassard-Hoyer-Tapp. Finds collisions in 2-to-1 functions. Only cubic root speedup. Used in quantum attacks on hash functions.", "reference": "arXiv:quant-ph/9705002"},
    {"name": "Element Distinctness", "category": "Search / Database", "speedup_class": "polynomial", "quantum_complexity": "O(N^(2/3))", "classical_best": "O(N)", "io_bottleneck": True, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "HPC_PREFERRED", "notes": "Ambainis quantum walk algorithm. Optimal. Generalizes to k-distinctness. Foundation for many quantum walk-based algorithms.", "reference": "arXiv:quant-ph/0311001"},
    {"name": "Welded Tree / Graph Traversal", "category": "Graph Problems", "speedup_class": "superpolynomial", "quantum_complexity": "poly(n)", "classical_best": "Exponential (provably)", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "Childs et al. Continuous-time quantum walk traverses welded binary trees exponentially faster. Provable exponential separation in oracle model.", "reference": "arXiv:quant-ph/0209131"},
    {"name": "Formula Evaluation (NAND Trees)", "category": "Boolean Functions", "speedup_class": "polynomial", "quantum_complexity": "O(N^(1/2))", "classical_best": "O(N^0.753)", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "INCONCLUSIVE", "notes": "Farhi-Goldstone-Gutmann quantum walk on NAND trees. Generalized by Reichardt span programs. Grover search is special case.", "reference": "arXiv:quant-ph/0702144"},
    {"name": "Hidden Shift", "category": "Oracle / Algebraic", "speedup_class": "superpolynomial", "quantum_complexity": "O(1) for multiplicative characters", "classical_best": "O(polylog(N)) not known classically", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "van Dam-Hallgren-Ip. Exponential speedup for shifted Legendre symbols and multiplicative characters.", "reference": "arXiv:quant-ph/0211140"},
    {"name": "Quantum Singular Value Transformation (QSVT)", "category": "Meta-Algorithm / Linear Algebra", "speedup_class": "superpolynomial", "quantum_complexity": "Optimal for many matrix problems", "classical_best": "Varies by application", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": True, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "Gilyen et al. Unifying framework subsuming Hamiltonian simulation, QPE, HHL, amplitude amplification.", "reference": "arXiv:1806.01838"},
    {"name": "Preparing Eigenstates and Thermal States", "category": "Quantum Simulation", "speedup_class": "superpolynomial", "quantum_complexity": "poly(n, 1/epsilon)", "classical_best": "Exponential in general", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": True, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "Quantum Gibbs sampling, adiabatic state preparation, imaginary time evolution. Essential for quantum chemistry.", "reference": "arXiv:2303.18224"},
    {"name": "Open Quantum System Simulation", "category": "Quantum Simulation", "speedup_class": "superpolynomial", "quantum_complexity": "poly(n, t, 1/epsilon)", "classical_best": "Exponential for general Lindbladian dynamics", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": True, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "Simulates Lindblad master equations, dissipative dynamics. Relevant for quantum optics, quantum biology, decoherence.", "reference": "arXiv:1612.09512"},
    {"name": "Knot and 3-Manifold Invariants", "category": "Topology", "speedup_class": "superpolynomial", "quantum_complexity": "BQP-complete", "classical_best": "#P-hard in general", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": True, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "Jones polynomial at roots of unity is BQP-complete (Freedman-Kitaev-Wang). Deep connection between QC and topology.", "reference": "arXiv:quant-ph/0511096"},
    {"name": "Partition Functions", "category": "Statistical Mechanics", "speedup_class": "superpolynomial", "quantum_complexity": "BQP-complete for certain cases", "classical_best": "#P-hard in general", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": True, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "Evaluating Potts model, Ising model partition functions. Tutte polynomial special cases.", "reference": "arXiv:quant-ph/0702008"},
    {"name": "Quantum Field Theory Simulation", "category": "High Energy Physics", "speedup_class": "superpolynomial", "quantum_complexity": "poly(1/epsilon, V, t)", "classical_best": "Sign problem for real-time; exponential for fermions", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": True, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "Jordan-Lee-Preskill framework. Simulates scattering in scalar and fermionic QFTs.", "reference": "arXiv:1111.3633"},
    {"name": "Simulated Annealing (Quantum Speedup)", "category": "Optimization / Monte Carlo", "speedup_class": "quadratic", "quantum_complexity": "O(1/sqrt(delta))", "classical_best": "O(1/delta)", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "HPC_PREFERRED", "notes": "Somma-Boixo. Quadratic speedup over classical simulated annealing via quantum walk on Markov chains.", "reference": "arXiv:0712.1008"},
    {"name": "Probabilistic Sampling (Quantum Supremacy)", "category": "Complexity Theory", "speedup_class": "superpolynomial", "quantum_complexity": "poly(n) for sampling", "classical_best": "Would collapse polynomial hierarchy", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": True, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "BosonSampling, random circuit sampling. Basis of quantum supremacy demonstrations.", "reference": "arXiv:1011.3245"},
    {"name": "Adiabatic Quantum Computation", "category": "Optimization", "speedup_class": "varies", "quantum_complexity": "O(1/gamma^2) where gamma is spectral gap", "classical_best": "Varies; NP-hard problems remain hard", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "INCONCLUSIVE", "notes": "Equivalent to circuit model with non-stoquastic Hamiltonians. Gap analysis notoriously hard.", "reference": "arXiv:quant-ph/0001106"},
    {"name": "Gradient Estimation", "category": "Optimization / Numerics", "speedup_class": "polynomial", "quantum_complexity": "O(1) queries for d-dimensional gradient", "classical_best": "O(d) queries", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "HPC_PREFERRED", "notes": "Jordan 2005. Single query estimates gradient. O(d) speedup for quadratic minimization.", "reference": "arXiv:quant-ph/0405146"},
    {"name": "Semidefinite Programming (Quantum)", "category": "Optimization", "speedup_class": "polynomial", "quantum_complexity": "O(m*log(m)*poly(log(n),r,1/eps))", "classical_best": "O(m*n*poly(r,1/eps))", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "HPC_PREFERRED", "notes": "Brandao-Svore. Quadratic speedup when rank r is small. Includes LP as special case.", "reference": "arXiv:1609.05537"},
    {"name": "Convex Optimization", "category": "Optimization", "speedup_class": "polynomial", "quantum_complexity": "Quadratic in dimension d", "classical_best": "Polynomial in d", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "HPC_PREFERRED", "notes": "General quadratic speedup in dimension for convex optimization and volume estimation.", "reference": "arXiv:1809.01731"},
    {"name": "Decoded Quantum Interferometry (DQI)", "category": "Optimization", "speedup_class": "superpolynomial", "quantum_complexity": "Depends on decoding radius", "classical_best": "No known poly-time classical algorithm", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "Jordan et al. (Nature 2025). Reduces optimization to decoding via QFT. Apparent exponential speedup for polynomial regression over finite fields.", "reference": "arXiv:2408.08292"},
    {"name": "Linear Differential Equations (Quantum)", "category": "Numerics / PDE", "speedup_class": "superpolynomial", "quantum_complexity": "O(t^2 * polylog(N, 1/eps))", "classical_best": "poly(N)", "io_bottleneck": True, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "INCONCLUSIVE", "notes": "Berry 2014. Exponential speedup in N but O(N) state prep + readout.", "reference": "arXiv:1010.2745"},
    {"name": "Nonlinear Differential Equations (Quantum)", "category": "Numerics / PDE", "speedup_class": "superpolynomial", "quantum_complexity": "O(t^2) via Carleman linearization", "classical_best": "poly(N)", "io_bottleneck": True, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "INCONCLUSIVE", "notes": "Carleman linearization approach. Limited to weakly nonlinear regime. Readout is O(N).", "reference": "arXiv:2011.03185"},
    {"name": "Quantum Monte Carlo Speedup", "category": "Monte Carlo / Finance", "speedup_class": "quadratic", "quantum_complexity": "O(1/epsilon)", "classical_best": "O(1/epsilon^2)", "io_bottleneck": True, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "HPC_PREFERRED", "notes": "Montanaro 2015. Quadratic speedup for MC integration. Applied to finance and fluid dynamics. I/O + QEC overhead limits advantage.", "reference": "arXiv:1504.06987"},
    {"name": "Quantum Topological Data Analysis", "category": "Machine Learning / Topology", "speedup_class": "superpolynomial", "quantum_complexity": "Exponential in Betti number computation", "classical_best": "Exponential for persistent homology", "io_bottleneck": True, "oracle_polynomial": False, "naturally_quantum": False, "troyer_verdict": "INCONCLUSIVE", "notes": "Lloyd-Garnerone-Zanardi. Computes Betti numbers. Data loading bottleneck. Partially dequantizable.", "reference": "arXiv:1408.3106"},
    {"name": "Quantum Support Vector Machine", "category": "Machine Learning", "speedup_class": "exponential_core", "quantum_complexity": "O(log(N)) kernel evaluation", "classical_best": "O(N) classical SVM", "io_bottleneck": True, "oracle_polynomial": False, "naturally_quantum": False, "troyer_verdict": "HPC_PREFERRED", "notes": "Rebentrost-Mohseni-Lloyd. Exponential kernel speedup IF data in QRAM. O(N) data loading negates advantage. Partially dequantized.", "reference": "arXiv:1307.0471"},
    {"name": "Quantum Recommendation Systems", "category": "Machine Learning", "speedup_class": "dequantized", "quantum_complexity": "O(polylog(mn))", "classical_best": "O(polylog(mn)) after Tang dequantization", "io_bottleneck": True, "oracle_polynomial": False, "naturally_quantum": False, "troyer_verdict": "HPC_PREFERRED", "notes": "Kerenidis-Prakash, dequantized by Tang 2018. Landmark result showing classical sampling matches quantum.", "reference": "arXiv:1807.04271"},
    {"name": "Quantum Dynamic Programming", "category": "Optimization / NP-hard", "speedup_class": "polynomial", "quantum_complexity": "O*(1.817^n)", "classical_best": "O*(2^n)", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "HPC_PREFERRED", "notes": "Ambainis et al. Combines Grover + DP. Speeds up TSP, vertex ordering, minimum set cover.", "reference": "arXiv:1807.05209"},
    {"name": "Quantum Backtracking", "category": "Constraint Satisfaction", "speedup_class": "polynomial", "quantum_complexity": "Quadratic speedup over classical backtracking", "classical_best": "Exponential (backtracking)", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "HPC_PREFERRED", "notes": "Montanaro 2015. General quantum speedup for backtracking via quantum walks. Applies to CSPs, SAT, graph coloring.", "reference": "arXiv:1509.02374"},
    {"name": "Lattice Problems (Quantum)", "category": "Cryptography / Optimization", "speedup_class": "superpolynomial", "quantum_complexity": "Polynomial for some parameter regimes", "classical_best": "No known poly-time for these regimes", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "INCONCLUSIVE", "notes": "Chen-Liu-Zhandry 2022. Does NOT break main post-quantum cryptosystems at standard parameters.", "reference": "arXiv:2108.11015"},
    {"name": "Coupled Classical Oscillators Simulation", "category": "Physics Simulation", "speedup_class": "superpolynomial", "quantum_complexity": "poly(n, t, 1/eps)", "classical_best": "Exponential for expander-graph connectivity", "io_bottleneck": False, "oracle_polynomial": True, "naturally_quantum": False, "troyer_verdict": "QUANTUM_ADVANTAGE", "notes": "Babbush et al. (PRX 2024). Exponential speedup for coupled harmonic oscillators on expander graphs. System is classical.", "reference": "arXiv:2303.13012"},
]

def main():
    existing = json.loads(ZOO_PATH.read_text(encoding="utf-8"))
    existing_algos = existing["algorithms"]
    existing_names = {a["name"] for a in existing_algos}

    added = [a for a in NEW_ALGORITHMS if a["name"] not in existing_names]
    all_algos = existing_algos + added

    speedup_summary = {}
    for a in all_algos:
        sc = a["speedup_class"]
        speedup_summary[sc] = speedup_summary.get(sc, 0) + 1

    data = {
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "source": "Curated from quantumalgorithmzoo.org + Troyer framework analysis (expanded April 2026)",
        "total_algorithms": len(all_algos),
        "algorithms": all_algos,
        "speedup_summary": speedup_summary,
    }

    ZOO_PATH.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Total: {len(all_algos)} algorithms ({len(added)} new)")
    print(f"Speedups: {json.dumps(speedup_summary)}")

if __name__ == "__main__":
    main()
