"""The published visualisation must not drift from the renders it claims to show.

`viz/` is the render pipeline and `website/` is the demo surface; they are owned by
different workstreams and joined by `viz/manifest.json`. `website/data/vizManifest.json`
is the published half, generated by `website/scripts/publish-viz.mjs` as an npm
`prebuild` step and committed so the page's import resolves on a fresh clone.

Committed generated data drifts. `docs/depgraph/` needed a CI check for exactly this
reason, and the estimate artifacts in #263 were fabricated for six months partly because
two stores existed with nothing comparing them.

What is checked here, and why each one:

- Every rendered problem upstream is published, and nothing is published that was not
  rendered. A poster that vanished upstream but lingers in the site is a claim about a
  run that no longer exists.
- The asset the manifest names exists and hashes to the declared sha256. An image is
  evidence about a run; an unverified copy is not.
- `alt` and `warnings` survive publication **verbatim**. The warnings say "this is not a
  quantum-state animation" and "neither demonstrates quantum advantage". A pretty render
  shown without them is precisely the over-claim this repository exists to avoid, and
  dropping them is a one-character change in the publisher.

The posters themselves are deliberately not committed under `website/public/` - they are
~29.5 MB and already tracked under `viz/assets`. The build republishes them.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_MANIFEST = REPO_ROOT / "viz" / "manifest.json"
PUBLISHED_MANIFEST = REPO_ROOT / "website" / "data" / "vizManifest.json"


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _rendered_upstream() -> dict[str, dict]:
    """Problems the render pipeline says it actually rendered."""
    manifest = _load(SOURCE_MANIFEST)
    return {
        problem["id"]: problem
        for problem in manifest["problems"]
        if problem.get("render_status") == "rendered" and problem.get("assets")
    }


def _published() -> dict[str, dict]:
    return {entry["id"]: entry for entry in _load(PUBLISHED_MANIFEST)["problems"]}


RENDERED = _rendered_upstream()
PUBLISHED = _published()


def test_there_is_something_to_publish():
    """Guard the guard: empty inputs would make every check below vacuous."""
    assert RENDERED, f"no rendered problems in {SOURCE_MANIFEST.name}"
    assert PUBLISHED, f"no published problems in {PUBLISHED_MANIFEST.name}"


def test_published_set_matches_the_rendered_set():
    missing = sorted(set(RENDERED) - set(PUBLISHED))
    extra = sorted(set(PUBLISHED) - set(RENDERED))
    assert not missing and not extra, (
        f"published visualisations have drifted from viz/manifest.json. "
        f"Rendered but not published: {missing or 'none'}. "
        f"Published but not rendered upstream: {extra or 'none'}. "
        f"Run `npm run publish-viz` in website/ and commit data/vizManifest.json."
    )


@pytest.mark.parametrize("problem_id", sorted(PUBLISHED), ids=sorted(PUBLISHED))
def test_published_poster_matches_its_source(problem_id):
    """The bytes on the site are the bytes the manifest vouches for."""
    upstream = RENDERED.get(problem_id)
    assert upstream, f"{problem_id}: published but not rendered upstream"

    asset = upstream["assets"][0]
    source = REPO_ROOT / "viz" / asset["path"]
    assert source.exists(), (
        f"{problem_id}: viz/manifest.json names {asset['path']}, which does not exist."
    )

    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    assert digest == asset["sha256"], (
        f"{problem_id}: {asset['path']} hashes to {digest[:12]} but the manifest declares "
        f"{asset['sha256'][:12]}. Regenerate the manifest, or restore the asset."
    )

    entry = PUBLISHED[problem_id]
    assert entry["poster"]["src"] == f"/viz/{problem_id}/poster.png", (
        f"{problem_id}: published poster src is {entry['poster']['src']!r}, which does not "
        f"match where the publisher writes the file."
    )
    assert entry["poster"]["width"] == asset["width"]
    assert entry["poster"]["height"] == asset["height"]


@pytest.mark.parametrize("problem_id", sorted(PUBLISHED), ids=sorted(PUBLISHED))
def test_the_caveats_survive_publication(problem_id):
    """The honesty text is the part most easily dropped, so it is asserted verbatim."""
    upstream = RENDERED[problem_id]
    entry = PUBLISHED[problem_id]

    assert entry["warnings"] == upstream.get("warnings", []), (
        f"{problem_id}: the published warnings differ from viz/manifest.json. These say the "
        f"render is not a quantum-state animation and demonstrates no advantage; publishing "
        f"the image without them would be an over-claim."
    )
    assert entry["poster"]["alt"] == upstream["assets"][0]["alt"], (
        f"{problem_id}: published alt text differs from the manifest."
    )
